### ISSUE TITLE
General comments

### ISSUE THREAD

**Issue by stropitek** [cheminfo-js/equilibrium2#3]
Here are some comments on your code. I think you really need to do major changes before going on and implementing new features. The more code you add the more difficult it will be to tidy afterwards.
### Top-level require

Do your `require` top level so that all functions in a file have access to it: avoid [this](https://github.com/cheminfo-js/equilibrium2/blob/ce478e241faec839a965fc91346fa93d6297fb18/src/ModelEquilibrium2.js#L9)
### Copy-paste

Don't copy paste code. Because when you edit some code that has been copied elsewhere you create two divergent versions of a piece of code and that's always bad. For example in the file `ModelEquilibrium2` there is copy-pasted code that has diverged on from another (one piece has a `Math.abs` that the other don't)
### Naming

Function and variable naming: try to be consistent. I noticed that some functions are named in french other in english...  Dont use uppercase as the first character of variables, unless it is a contstructor function.
More importantly give your functions names such that it's easy to understand what they do. For example it's easy to understand `calculateTotalConcentrationSpecies` but hard to understand `compareRealAndCalcTotalConcentration`. If it's hard to find a name, it's probably that what the function does is too complicated or that it does more than 1 thing, which it shouldn't.
### Functions

A common bad practice I see in your code is using function to modify its arguments. In order to avoid unppredictable side-effects, functions are units that should take an input, calculate some output based on it._But in most cases it should not modify the input_ . That way a function is a independent unit that doesn't affect other parts of the code.
### File structure

Use directories to categorize your files. For example you've named a lot of files ending them with "Equilibrium2" when you could have namespace those files just by creating a directory `equilibrium2`. In `src` there should only be the core source code, not examples. `testConstant.js` for example should be in a separate directory.
### Unused variables

Try to clean up your code from unused variables, there seem to be a lot of them and they make the code more difficult to apprehend. In webstorm ununsed variables can be spotted easily.
### Prevent bugs before they happen

I will install a tool that is called es-lint, that will enable you to correct some sources of bugs. For example you have:

``` js
if(relativeError==NaN)
```

which will always be `false`, so there is something wrong. Those kind of errors can be spotted by a tool like es-lint.
### Unit tests

Try to write as many unit tests as you can. For now only matrix has unit tests. I would nice if the core of the algorithm was also tested. Try to separate your algorithm in simple parts for which you can predict output based on input and test them.
### Code indenting

You should use code indenting properly. Code is hard to read when it's not properly indented. You code should be indented automatically if you use Webstorm.

**Comment by minibrasiler** [comment]
Thanks for your comments,
I begin to correct my code by I have some difficulties.
For the top-level require: if i put the require in the export function above all function it doesn’t work. If I put it outside the export function. The function inside the export that called an other function in the same class can’t do it anymore.
Copy-paste: I don’t understand why is it bas to have two function that diverge ? Two function doesn’t have to do the same thing… I think ?
Naming: I don’t understand what do you about a function that doing one thing. Just one line of code? It’s very a very small function…
File structure: All the tests like testConstant.js in the src will be destroy at the end of my work.

For the rest of the comment is OK for me i will do my best to change this.


Le 13 mai 2016 à 16:17, Daniel Kostro <notifications@github.com<mailto:notifications@github.com>> a écrit :


Here are some comments on your code. I think you really need to do major changes before going on and implementing new features. The more code you add the more difficult it will be to tidy afterwards.

Top-level require

Do your require top level so that all functions in a file have access to it: avoid this<https://github.com/cheminfo-js/equilibrium2/blob/ce478e241faec839a965fc91346fa93d6297fb18/src/ModelEquilibrium2.js#L9>

Copy-paste

Don't copy paste code. Because when you edit some code that has been copied elsewhere you create two divergent versions of a piece of code and that's always bad. For example in the file ModelEquilibrium2 there is copy-pasted code that has diverged on from another (one piece has a Math.abs that the other don't)

Naming

Function and variable naming: try to be consistent. I noticed that some functions are named in french other in english... Dont use uppercase as the first character of variables, unless it is a contstructor function.
More importantly give your functions names such that it's easy to understand what they do. For example it's easy to understand calculateTotalConcentrationSpecies but hard to understand compareRealAndCalcTotalConcentration. If it's hard to find a name, it's probably that what the function does is too complicated or that it does more than 1 thing, which it shouldn't.

File structure

Use directories to categorize your files. For example you've named a lot of files ending them with "Equilibrium2" when you could have namespace those files just by creating a directory equilibrium2. In src there should only be the core source code, not examples. testConstant.js for example should be in a separate directory.

Unused variables

Try to clean up your code from unused variables, there seem to be a lot of them and they make the code more difficult to apprehend. In webstorm ununsed variables can be spotted easily.

Prevent bugs before they happen

I will install a tool that is called es-lint, that will enable you to correct some sources of bugs. For example you have:

if(relativeError==NaN)

which will always be false, so there is something wrong. Those kind of errors can be spotted by a tool like es-lint.

Unit tests

Try to write as many unit tests as you can. For now only matrix has unit tests. I would nice if the core of the algorithm was also tested. Try to separate your algorithm in simple parts for which you can predict output based on input and test them.

Code indenting

You should use code indenting properly. Code is hard to read when it's not properly indented. You code should be indented automatically if you use Webstorm.
